Update command
buildkite-plugins/monorepo-diff-buildkite-plugin pull request #2
Opened 2023-10-28 01:49 UTC by stephanieatte

2023-11-27 22:51 UTC, pzeballos commented
hey @stephanieatte ! Is this PR ready for review? If so, can you add more details on what it does, how to test it, explain the changes, etc. Thanks!

2023-11-28 18:00 UTC, stephanieatte commented
@pzeballos not yet. It's the random pr since before. I will update with the new changes etc

2023-12-19 20:37 UTC, pzeballos requested changes
Good! Only a small change :)

2023-12-19 20:37 UTC, pzeballos commented on .gitignore
> +dist/
You can remove one of them

2023-12-20 17:57 UTC, stephanieatte commented on .gitignore
> +dist/
Done

2023-12-20 17:57 UTC, merged